hash-format = "sha256"

[[files]]
file = "CHANGELOG.md"
hash = "2ba42ee9ede6030cd791362d260c901eac75cb4daed3c387b4f926b277f09247"

[[files]]
file = "config/fancymenu/config.txt"
hash = "a68403d921757907ccc6db84c8ad9c857b437bfc52215638f0e94a9bf043ee63"

[[files]]
file = "config/fancymenu/custom_gui_screens.txt"
hash = "ff492043eaf454c46e949d5eef32ece90cc5a19feb50a161dd29a43b5732c880"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "9d908fb21b9f0ad86f2b9342c243ee92a3bcb6492caf1b794565be3fef62e04e"

[[files]]
file = "config/fancymenu/customization/loading.txt"
hash = "bc7f8408c9486e43316639be9e05cf89a261b395a0fa321e982cc2c71e39e86e"

[[files]]
file = "config/fancymenu/customization/wynn.txt"
hash = "fefc9ab1b9c7db942f8ad33b797512cc42d3da5f3685ada2dd070ed63a0b9a92"

[[files]]
file = "config/fancymenu/layout_editor/widgets/element_layer_control.lewidget"
hash = "051d700ea7ff1bd626063d60f9a9cd65a0af1fed5903706d1e70fce20bcb2495"

[[files]]
file = "config/fancymenu/legacy_checklist.txt"
hash = "9a25d3dc708e43eabafce5479a13c02dae15bc7f673afb2745b8b2ba48a97dc0"

[[files]]
file = "config/fancymenu/menu_identifiers.db"
hash = "003a1c89846741e0eb9475089d4ed653896fd08e0b994667fae452b4ad894a72"

[[files]]
file = "config/fancymenu/options.txt"
hash = "c130ac7e4c8a7316652022b53fff0c2774d78296e93b8f797d2542274c1b5d78"

[[files]]
file = "config/fancymenu/user_variables.db"
hash = "4cf594f4299aaebc575513966d5aa2dca5559621a5b53c647fea12a178de9b71"

[[files]]
file = "config/fancymenu/wynn/background.png"
hash = "6c11323734e7281caef8bc336e6eb4571a90d0b71b44f3afd02d1c3a2ffe0fb5"

[[files]]
file = "config/fancymenu/wynn/wynncraft_logo.png"
hash = "d6ca61843ad84e0c0f93fca5ed2a6f6ee9a8aadf898ffd312ad5323263df0448"

[[files]]
file = "config/version.txt"
hash = "363a921a3409b977e99e614346401fcac4888ac322078dfcc152fc435bed56f3"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "1433d3b049af59d534211442102a81613adab4a2922e3f8dc0252d8b7157b508"

[[files]]
file = "config/yosbr/config/shouldersurfing.toml"
hash = "689a1d3dac47acc9dff4a84d6e91142f54fa4146ef6409c164496c807625cd95"

[[files]]
file = "config/yosbr/options.txt"
hash = "f455074843b25a83e9497e0317d30bc43b5125a676466876e83cd6bd580e9af8"

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "df15648dd4d4e27dd0c45ab4e78277c45886b77a698b129f4ce2d2bc337f7044"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "f32c30de1ae7dbeeae00b654eb15ea358c6d26f631dc292bdb88dba9c30a8cc8"
metafile = true

[[files]]
file = "mods/drippy-loading-screen.pw.toml"
hash = "471c976b987c0b78a37793e4d483626a0601aae293e7da91be74c75e44936cac"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c171246e9496f4a42a984da40a24413d29f804077c1c93bf034532729d269bf9"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "18e346acc11ee4082d56b804810909a69010a26eb27ac1ac3840489a6ed754fb"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "f217a0233c8aef84e914e1f8e90718be2496a923725215190d375ab3140379ab"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "e77ea5430e509bbebccb49d2df408e4cd20f6707105b88bda0578189cdfa7e8e"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d5b02cdd8918d1e509bbedd2d7073544110a5985f6b94cbc799464324ee0d1ba"
metafile = true

[[files]]
file = "mods/fuy_gg.pw.toml"
hash = "ab442e641e5ff8571576f3ef3a0428717eeb343a194ccad16b6d89dafbac2d1d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "eec54c8310038eaf8625ace2ab01e8ca6b1ce68b0e6a051835cf2faf324478c6"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e03fc0b0c151c5c072ac399d27b5c4268a093c41be73f3b1578d050bb49211f3"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "dafb84b20ceb9f80a2f98170a05b90a7225bc476f64593af2a51d332055b2e8b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "df9d69dc784ef61e99064407952d34c294f62fe1155b5260f825bd9a82e2f3a2"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "ab6af5e589ade8a9400eba7235ee509e66f640cd248bf3333b6001a084d63b3e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a874985359eaa4317b3242136fe65b86207a6d5ab55e0b4aa8f37b90727f0487"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "4cee088bfe934c92a726955d4fc6f46828b4a92e54204dfa2742b54d2291e4c4"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "a3b6cfe494d8ca3b080ce18d94d3218d7a76545d8b05e3f0b92a2b15c45c97dd"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "51c556d345a399e4bd7e31411d94fa0e5f7aeb58d8073c8302b62c7001cbb86c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "95d3b6b7cce5a872c83311cf503d5e5c6018b7cfbb078d42a1211f2960e50918"
metafile = true

[[files]]
file = "mods/vow.pw.toml"
hash = "6a517abb2f5aaef8ef2500f18d5a80ad8365e5491decd02b3b701051899bd9c3"
metafile = true

[[files]]
file = "mods/wynntils.pw.toml"
hash = "034c15e2a5196cb3d2361d1b204b8330d604a68f301cc18a3527a195ca5258ab"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "options.txt"
hash = "f455074843b25a83e9497e0317d30bc43b5125a676466876e83cd6bd580e9af8"

[[files]]
file = "resourcepacks/panorama/assets/minecraft/textures/gui/title/background/panorama_0.png"
hash = "97adf8510409c53c18df582bd15c850c6ecc9160d388181f0dd1efde7cd208e3"

[[files]]
file = "resourcepacks/panorama/assets/minecraft/textures/gui/title/background/panorama_1.png"
hash = "d2a459db13600508e6cdaaefa386cb49738e0b3939ad45716d008ae8b30fb70c"

[[files]]
file = "resourcepacks/panorama/assets/minecraft/textures/gui/title/background/panorama_2.png"
hash = "535677c3fea5d236b22f1aee7c1eefcee5d1d5b825900ee489101afb170a62bb"

[[files]]
file = "resourcepacks/panorama/assets/minecraft/textures/gui/title/background/panorama_3.png"
hash = "5e4268f2953805ab0c48bc32a087077e58ff9e067cf9dfecec16b08a097d8f1f"

[[files]]
file = "resourcepacks/panorama/assets/minecraft/textures/gui/title/background/panorama_4.png"
hash = "65adc77bf14c3db336e538b1525b5e492b65435b66a147748d3032f29d0f560c"

[[files]]
file = "resourcepacks/panorama/assets/minecraft/textures/gui/title/background/panorama_5.png"
hash = "3a22e3be99980697218cd995c7de3c963e01ed9294fd8739b1109d39f4b22192"

[[files]]
file = "resourcepacks/panorama/assets/minecraft/textures/gui/title/background/panorama_overlay.png"
hash = "4cabea349b45c137de6ab4472303fb20fb94b07a119c8926aa54575ffbab91e6"

[[files]]
file = "resourcepacks/panorama/pack.mcmeta"
hash = "4a7c69e0ef0b9e78d060be65c12aec99fdf4bb760d912256fada5b8b86d21920"

[[files]]
file = "servers.dat"
hash = "fe802fe3c4fa7db905a7cb52ac50f18295d48ae695072bb8ec3b287677a64e2e"

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "9025311f42fe8ab581987962c9c6b3ec5a50f5afc803e9d867dc580cb0b66190"
metafile = true
