name = "Wynncraft 101"
author = "aninus"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cca07a9acd0ed2d797a9a97beae9c2c20602ee7a5a2931a069557e07faf52210"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
